// <auto-generated />
using System;
using BeerService.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BeerService.Data.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20200621225749_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BeerService.Domain.Entities.Cerveja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Cor")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Harmonizacao")
                        .HasColumnType("text");

                    b.Property<string>("Ingredientes")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<decimal>("TemperaturaFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TemperaturaInicial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TeorAlcoolico")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Cervejas");
                });

            modelBuilder.Entity("BeerService.Domain.Entities.Imagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caminho")
                        .HasColumnType("text");

                    b.Property<Guid?>("CervejaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CervejaId");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("BeerService.Domain.Entities.Imagem", b =>
                {
                    b.HasOne("BeerService.Domain.Entities.Cerveja", null)
                        .WithMany("Imagens")
                        .HasForeignKey("CervejaId");
                });
#pragma warning restore 612, 618
        }
    }
}
